# Generated by Django 5.0.6 on 2024-05-16 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('unique_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('district', models.CharField(max_length=100)),
                ('chapter', models.CharField(max_length=100)),
                ('validity_date', models.DateField()),
                ('is_valid', models.BooleanField(default=False)),
            ],
        ),
    ]
