# Generated by Django 5.0.6 on 2024-05-22 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_person_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='is_valid',
        ),
    ]
